"""Acceptance tests for REQ-006 AC1-AC4 — the Word (.docx) importer.

These prove the *mechanism* against fixtures whose expected output is known by construction
(``test_data/Word/``, generated by the ``build_fixtures.py`` beside them). What they cannot
prove is *yield* over 342 real documents, which is why REQ-006 Decision 9 makes the corpus
run a develop-session obligation and AC5 grades the settled outcome on the deployed instance.

No document from the household collection is committed; every fixture is written here, to the
collection's conventions, with the German style ids Word actually emits.
"""
import os
import re
from io import BytesIO
from zipfile import ZipFile

import pytest
from django.contrib import auth
from django.test import RequestFactory
from django_scopes import scope

from cookbook.forms import ImportExportBase, ImportForm
from cookbook.helper.word_parser import EmptyDocument, UnparseableDocument, WordDocumentSkipped, parse_docx
from cookbook.integration.word import Word
from cookbook.models import ImportLog, Keyword, Recipe
from cookbook.views.import_export import get_integration

FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'test_data', 'Word')

#: the layout AC3's zip is built in: category folder, print subfolder, file
ZIP_LAYOUT = (
    ('Fleisch/Ausgedruckte Rezepte mit Bild/canonical.docx', 'canonical.docx'),
    ('Nudelgerichte/plain.docx', 'plain.docx'),
    ('Fleisch/table_ingredients.docx', 'table_ingredients.docx'),
    ('Nudelgerichte/no_recipe.docx', 'no_recipe.docx'),
)

PRINT_SUBFOLDER = 'Ausgedruckte Rezepte mit Bild'


def fixture_bytes(name):
    with open(os.path.join(FIXTURES, name), 'rb') as f:
        return f.read()


def request_generator(u1_s1):
    user = auth.get_user(u1_s1)
    space = user.userspace_set.first().space
    request = RequestFactory()
    request.user = user
    request.space = space
    return space, request


def build_zip():
    stream = BytesIO()
    with ZipFile(stream, 'w') as archive:
        for path, source in ZIP_LAYOUT:
            archive.writestr(path, fixture_bytes(source))
    stream.seek(0)
    stream.name = 'Rezepte.zip'
    return stream


def test_canonical_document_extraction():
    """AC1 — every canonical signal comes out of a document written to the conventions."""
    recipe = parse_docx(fixture_bytes('canonical.docx'))

    assert recipe.name == 'Nussecken vom Blech', 'the Titel-styled paragraph is the recipe name'

    # servings, from the ingredient heading's trailing phrase, in digit form
    assert recipe.servings == 4
    assert recipe.servings_text == 'Personen'

    assert len(recipe.components) == 2, 'a further "Zutaten für X" heading opens a second component'

    main, filling = recipe.components

    assert main.name == '', 'the yield heading opens the recipe itself, not a named part'
    assert main.ingredients == [
        '375 g Weizenmehl (550er)',
        '1 Tl Backpulver',
        '130 g Butter',
        '2 Eier',
    ], 'every bulleted line under the Zutaten heading, raw and in document order'
    assert main.instructions == [
        'Aus den Teigzutaten einen Knetteig verarbeiten.',
        'Den Backofen auf 175°C Ober-/Unterhitze vorheizen.',
        'Den Teig auf einem gefetteten Backblech ausrollen.',
    ], 'every body paragraph under the Zubereitung heading, one step each, in document order'

    assert filling.name == 'Füllung', 'the component is named for what its heading says it is'
    assert filling.ingredients == ['200 g gemahlene Haselnüsse', '3 El Wasser'], 'the component carries its own ingredients'
    assert filling.instructions == [
        'Die Nüsse mit dem Wasser verrühren.',
        'Die Masse auf den Teig geben und 25 Minuten backen.',
    ], 'the component carries its own following instructions'

    # the first embedded photograph, as bytes plus its file type
    assert recipe.image_filetype == '.jpg'
    assert isinstance(recipe.image, bytes) and recipe.image[:2] == b'\xff\xd8', 'the image bytes are the JPEG that was embedded'

    # a German number word resolves to the same integer a digit would, and the rest of the
    # phrase survives as servings text
    spelled = parse_docx(fixture_bytes('servings_number_word.docx'))
    assert (spelled.servings, spelled.servings_text) == (6, 'Brezeln (ein Blech)')

    # nothing resolvable in the phrase leaves the count at its default and keeps the words
    unresolvable = parse_docx(fixture_bytes('servings_unresolvable.docx'))
    assert (unresolvable.servings, unresolvable.servings_text) == (1, 'die ganze Familie')


def test_unparseable_and_empty_documents_are_rejected():
    """AC2 — the parser refuses rather than guesses, and says why."""
    with pytest.raises(UnparseableDocument) as refused:
        parse_docx(fixture_bytes('table_ingredients.docx'))
    assert 'table' in refused.value.reason, 'the rejection names the shape that caused it'
    assert isinstance(refused.value, WordDocumentSkipped)

    # the failure this is really about: not that it raised, but that it did not quietly
    # produce a recipe whose ingredient list is its method
    with pytest.raises(WordDocumentSkipped):
        parse_docx(fixture_bytes('table_ingredients.docx'))

    with pytest.raises(EmptyDocument) as headings:
        parse_docx(fixture_bytes('empty_headings.docx'))
    assert headings.value.reason, 'an empty document is rejected with a reason too'

    with pytest.raises(EmptyDocument):
        parse_docx(fixture_bytes('no_recipe.docx'))


def test_zip_import_creates_recipes_with_folder_keywords(u1_s1):
    """AC3 — a zip of documents imports end to end, skipping what it must and logging why."""
    space, request = request_generator(u1_s1)

    with scope(space=space):
        integration = get_integration(request, ImportExportBase.WORD)
        il = ImportLog.objects.create(type=ImportExportBase.WORD, created_by=request.user, space=space)

        integration.do_import([{'file': build_zip(), 'name': 'Rezepte.zip'}], il, False)

        il.refresh_from_db()
        imported = Recipe.objects.filter(keywords=integration.keyword)
        assert {r.name for r in imported} == {'Nussecken vom Blech', 'Kartoffelsalat'}, 'exactly the valid documents became recipes'

        nussecken = imported.get(name='Nussecken vom Blech')

        # ingredients resolved to Food and Unit objects by IngredientParser
        steps = list(nussecken.steps.all())
        assert [s.instruction for s in steps] == [
            'Aus den Teigzutaten einen Knetteig verarbeiten.',
            'Den Backofen auf 175°C Ober-/Unterhitze vorheizen.',
            'Den Teig auf einem gefetteten Backblech ausrollen.',
            'Die Nüsse mit dem Wasser verrühren.',
            'Die Masse auf den Teig geben und 25 Minuten backen.',
        ], 'one step per Word paragraph, in document order'
        assert [s.name for s in steps] == ['', '', '', 'Füllung', ''], 'the component names its own first step'

        first = [(i.food.name, i.unit.name if i.unit else None, float(i.amount), i.note) for i in steps[0].ingredients.all().order_by('pk')]
        assert first == [
            ('Weizenmehl', 'g', 375.0, '550er'),
            ('Backpulver', 'Tl', 1.0, ''),
            ('Butter', 'g', 130.0, ''),
            ('Eier', None, 2.0, ''),
        ], 'the recipe ingredients hang off its first step, split into Food, Unit and note'
        assert [str(i.food)
                for i in steps[3].ingredients.all().order_by('pk')] == ['gemahlene Haselnüsse', 'Wasser'], "the component's ingredients hang off the component's first step"

        assert nussecken.image, 'the embedded photograph was attached'
        assert nussecken.servings == 4 and nussecken.servings_text == 'Personen'

        # the top-level folder is a keyword; the print subfolder is nowhere in the tree
        assert 'Fleisch' in {k.name for k in nussecken.keywords.all()}
        assert 'Nudelgerichte' in {k.name for k in imported.get(name='Kartoffelsalat').keywords.all()}
        assert not Keyword.objects.filter(name=PRINT_SUBFOLDER, space=space).exists(), 'the print subfolder level never becomes a keyword'

        # the skipped documents are named with their reason, and did not abort the run
        assert 'Fleisch/table_ingredients.docx' in il.msg
        assert 'table' in il.msg
        assert 'Nudelgerichte/no_recipe.docx' in il.msg
        assert il.imported_recipes == 2
        assert not il.running, 'the run finished rather than dying on the first bad document'


def test_word_type_is_reachable_from_every_registry(u1_s1):
    """AC4 — an integration that exists but is not wired up is not a feature."""
    space, request = request_generator(u1_s1)

    assert ImportExportBase.WORD in dict(ImportForm().fields['type'].choices), 'the Django import form offers the WORD type'

    with scope(space=space):
        assert isinstance(get_integration(request, ImportExportBase.WORD), Word), 'get_integration dispatches WORD to the Word integration'

    registry = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', 'vue3', 'src', 'utils', 'integration_utils.ts')
    with open(os.path.normpath(registry), encoding='utf-8') as f:
        source = f.read()
    row = re.search(r"^\s*\{id:\s*'WORD'.*$", source, re.MULTILINE)
    assert row, 'the frontend integration registry has a WORD row'
    assert re.search(r'import:\s*true', row.group(0)), 'the frontend registry marks WORD importable'
