# Generated by Django 5.2.15 on 2026-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='use_readable_time',
            field=models.BooleanField(default=False),
        ),
    ]
