# Generated by Django 5.2.15 on 2026-09-07 10:43

"""Drop UserPreference.use_readable_time — readable durations are unconditional (REQ-010).

REQ-003 added the preference because ``use_fractions`` was a worn seam for a per-user display
toggle. Upstream declined it on PR #4785 ("I do not think we need the user preference. Just show
the times in a human readable format"), and REQ-010 Decision 3 takes it out here too rather than
have this fork carry a schema difference it is simultaneously asking upstream not to take.

Accepted data loss: nothing records what any account had the flag set to, so the reverse
migration recreates the column at its ``True`` default rather than restoring a choice. On this
instance every account was at that default, so the loss is nominal — it is stated because it is
real. Nothing about what a user *sees* changes: the display path now formats unconditionally,
which is what a ``True`` flag already did.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0244_step_working_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='use_readable_time',
        ),
    ]
